# Use the official Python image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app/src/

# Copy the requirements file into the container
COPY ./my-python-project/src/requirements.txt /app/src/
# Ensure the data directory is copied
COPY ./my-python-project/src/data /app/src/data
# Install dependencies
RUN pip install --upgrade pip
# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the Python script
CMD ["python", "main.py"]