name: Daily Python Script

on:
  push:  # Trigger the workflow on push to the repository
    branches:
      - main  # Specify the branch to watch (e.g., 'main')

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-script .

      - name: Run script
        env:
          TEST_FILE_NAME: ${{ secrets.TEST_FILE_NAME }}
        run: docker run --rm -e TEST_FILE_NAME=$TEST_FILE_NAME -v ${{ github.workspace }}/my-python-project:/app my-script

      - name: Commit and push DB
        env:
          GH_PAT: ${{ secrets.COMMIT_TOKET }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add .
          git commit -m "Test workflow on $(date)"
          git push